using System.IO;
using System.IO.Compression;
using System.Text;

namespace FieldPulseSIP;

/// <summary>
/// Generates brand-specific SIP provisioning configuration files.
/// Passwords are left as placeholders — customers or FieldPulse set them during onboarding.
/// </summary>
public static class ProvisioningGenerator
{
    public static byte[] GenerateZip(
        List<PhoneEntry> phones,
        string sipServer,
        string sipPort,
        string transport,
        string outboundProxy,
        string voicemailExt)
    {
        using var ms = new MemoryStream();
        using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, leaveOpen: true))
        {
            foreach (var phone in phones)
            {
                string brand = NormalizeBrand(phone.Brand);
                string filename = BuildFilename(brand, phone);
                string content = brand switch
                {
                    "yealink"     => GenerateYealink(phone, sipServer, sipPort, transport, outboundProxy, voicemailExt),
                    "polycom"     => GeneratePolycom(phone, sipServer, sipPort, transport, outboundProxy, voicemailExt),
                    "cisco"       => GenerateCisco(phone, sipServer, sipPort, transport, outboundProxy, voicemailExt),
                    "grandstream" => GenerateGrandstream(phone, sipServer, sipPort, transport, outboundProxy, voicemailExt),
                    "fanvil"      => GenerateFanvil(phone, sipServer, sipPort, transport, outboundProxy, voicemailExt),
                    "snom"        => GenerateSnom(phone, sipServer, sipPort, transport, outboundProxy, voicemailExt),
                    _             => GenerateGeneric(phone, sipServer, sipPort, transport, outboundProxy, voicemailExt, brand),
                };

                var entry = zip.CreateEntry($"configs/{filename}", CompressionLevel.Optimal);
                using var writer = new StreamWriter(entry.Open(), Encoding.UTF8);
                writer.Write(content);
            }

            // Add a README
            var readme = zip.CreateEntry("configs/README.txt", CompressionLevel.Optimal);
            using var readmeWriter = new StreamWriter(readme.Open(), Encoding.UTF8);
            readmeWriter.Write(BuildReadme(phones.Count, sipServer, transport));
        }

        return ms.ToArray();
    }

    private static string NormalizeBrand(string brand)
    {
        string lower = brand.ToLowerInvariant().Trim();
        if (lower.Contains("yealink"))     return "yealink";
        if (lower.Contains("polycom") || lower.Contains("poly")) return "polycom";
        if (lower.Contains("cisco"))       return "cisco";
        if (lower.Contains("grandstream")) return "grandstream";
        if (lower.Contains("fanvil"))      return "fanvil";
        if (lower.Contains("snom"))        return "snom";
        return lower;
    }

    private static string BuildFilename(string brand, PhoneEntry phone)
    {
        string mac = phone.MACAddress.Replace(":", "").ToLower();
        string ext = string.IsNullOrEmpty(phone.Extension) ? "noext" : phone.Extension;
        return brand switch
        {
            "yealink"     => $"{mac}.cfg",
            "polycom"     => $"{mac}-phone.cfg",
            "cisco"       => $"SEP{mac.ToUpper()}.cnf.xml",
            "grandstream" => $"cfg{mac}.xml",
            "fanvil"      => $"{mac}.cfg",
            "snom"        => $"snom{mac}.xml",
            _             => $"{brand}_{ext}_{mac}.cfg",
        };
    }

    private static string TransportCode(string transport, string brand) => brand switch
    {
        "yealink" => transport.ToUpper() switch { "TCP" => "1", "TLS" => "2", _ => "0" },
        "grandstream" => transport.ToUpper() switch { "TCP" => "1", "TLS" => "2", _ => "0" },
        "fanvil" => transport.ToUpper() switch { "TCP" => "1", "TLS" => "2", _ => "0" },
        _ => transport.ToUpper(),
    };

    // ── Yealink ──────────────────────────────────────────────────────
    private static string GenerateYealink(PhoneEntry p, string server, string port, string transport, string proxy, string vm)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!version:1.0.0.1");
        sb.AppendLine($"## Yealink Provisioning Config — {p.DisplayName} (Ext {p.Extension})");
        sb.AppendLine($"## Phone Model: {p.PhoneModel}  MAC: {p.MACAddress}");
        sb.AppendLine($"## Generated by FieldPulse SIP Readiness Tool");
        sb.AppendLine();
        sb.AppendLine("account.1.enable = 1");
        sb.AppendLine($"account.1.label = {(string.IsNullOrEmpty(p.DisplayName) ? p.Extension : p.DisplayName)}");
        sb.AppendLine($"account.1.display_name = {(string.IsNullOrEmpty(p.DisplayName) ? p.Extension : p.DisplayName)}");
        sb.AppendLine($"account.1.auth_name = {p.Extension}");
        sb.AppendLine($"account.1.user_name = {p.Extension}");
        sb.AppendLine("account.1.password = [SET_PASSWORD]");
        sb.AppendLine($"account.1.sip_server.1.address = {server}");
        sb.AppendLine($"account.1.sip_server.1.port = {port}");
        sb.AppendLine($"account.1.sip_server.1.transport_type = {TransportCode(transport, "yealink")}");
        sb.AppendLine("account.1.sip_server.1.expires = 3600");
        if (!string.IsNullOrEmpty(proxy))
        {
            sb.AppendLine("account.1.outbound_proxy_enable = 1");
            sb.AppendLine($"account.1.outbound_proxy.1.address = {proxy}");
            sb.AppendLine($"account.1.outbound_proxy.1.port = {port}");
        }
        if (!string.IsNullOrEmpty(vm))
        {
            sb.AppendLine($"voice_mail.number.1 = {vm}");
        }
        sb.AppendLine();
        sb.AppendLine("## Codec preferences (G.711u preferred for LAN)");
        sb.AppendLine("account.1.codec.1.enable = 1");
        sb.AppendLine("account.1.codec.1.payload_type = PCMU");
        sb.AppendLine("account.1.codec.1.priority = 1");
        sb.AppendLine("account.1.codec.2.enable = 1");
        sb.AppendLine("account.1.codec.2.payload_type = PCMA");
        sb.AppendLine("account.1.codec.2.priority = 2");
        sb.AppendLine("account.1.codec.3.enable = 1");
        sb.AppendLine("account.1.codec.3.payload_type = G729");
        sb.AppendLine("account.1.codec.3.priority = 3");
        return sb.ToString();
    }

    // ── Polycom ──────────────────────────────────────────────────────
    private static string GeneratePolycom(PhoneEntry p, string server, string port, string transport, string proxy, string vm)
    {
        string displayName = string.IsNullOrEmpty(p.DisplayName) ? p.Extension : Xml(p.DisplayName);
        return $"""
            <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <!-- Polycom Provisioning Config — {Xml(p.DisplayName)} (Ext {p.Extension}) -->
            <!-- Phone Model: {Xml(p.PhoneModel)}  MAC: {p.MACAddress} -->
            <!-- Generated by FieldPulse SIP Readiness Tool -->
            <polycomConfig>
              <reg
                reg.1.address="{p.Extension}"
                reg.1.auth.userId="{p.Extension}"
                reg.1.auth.password="[SET_PASSWORD]"
                reg.1.displayName="{displayName}"
                reg.1.label="{displayName}"
                reg.1.type="private"
                reg.1.server.1.address="{Xml(server)}"
                reg.1.server.1.port="{port}"
                reg.1.server.1.transport="{transport}"
                reg.1.server.1.expires="3600"
              />
              {(string.IsNullOrEmpty(proxy) ? "" : $"<reg reg.1.outboundProxy.address=\"{Xml(proxy)}\" reg.1.outboundProxy.port=\"{port}\"/>")}
              {(string.IsNullOrEmpty(vm) ? "" : $"<msg msg.mwi.1.callBackMode=\"contact\" msg.mwi.1.callBack=\"{vm}\"/>")}
              <voice
                voice.codecPref.G711Mu="1"
                voice.codecPref.G711A="2"
                voice.codecPref.G729AB="3"
              />
            </polycomConfig>
            """;
    }

    // ── Cisco ────────────────────────────────────────────────────────
    private static string GenerateCisco(PhoneEntry p, string server, string port, string transport, string proxy, string vm)
    {
        string displayName = string.IsNullOrEmpty(p.DisplayName) ? p.Extension : Xml(p.DisplayName);
        string mac = p.MACAddress.Replace(":", "").ToUpper();
        return $"""
            <?xml version="1.0" encoding="UTF-8"?>
            <!-- Cisco SIP Phone Config — {Xml(p.DisplayName)} (Ext {p.Extension}) -->
            <!-- Phone Model: {Xml(p.PhoneModel)}  MAC: {p.MACAddress} -->
            <!-- Generated by FieldPulse SIP Readiness Tool -->
            <device>
              <deviceProtocol>SIP</deviceProtocol>
              <devicePool>
                <dateTimeSetting>
                  <dateTemplate>M/D/Y</dateTemplate>
                  <timeZone>Central Standard/Daylight Time</timeZone>
                </dateTimeSetting>
              </devicePool>
              <sipProfile>
                <sipProxies>
                  <outboundProxy>{(string.IsNullOrEmpty(proxy) ? Xml(server) : Xml(proxy))}</outboundProxy>
                  <outboundProxyPort>{port}</outboundProxyPort>
                </sipProxies>
                <sipLines>
                  <line button="1">
                    <featureID>9</featureID>
                    <proxy>{Xml(server)}</proxy>
                    <port>{port}</port>
                    <name>{p.Extension}</name>
                    <displayName>{displayName}</displayName>
                    <authName>{p.Extension}</authName>
                    <authPassword>[SET_PASSWORD]</authPassword>
                    <preferredCodec>g711ulaw</preferredCodec>
                    {(string.IsNullOrEmpty(vm) ? "" : $"<messagesNumber>{vm}</messagesNumber>")}
                  </line>
                </sipLines>
                <preferredCodec>g711ulaw</preferredCodec>
                <transportLayerProtocol>{(transport.ToUpper() == "TLS" ? "4" : transport.ToUpper() == "TCP" ? "2" : "1")}</transportLayerProtocol>
              </sipProfile>
            </device>
            """;
    }

    // ── Grandstream ──────────────────────────────────────────────────
    private static string GenerateGrandstream(PhoneEntry p, string server, string port, string transport, string proxy, string vm)
    {
        string displayName = string.IsNullOrEmpty(p.DisplayName) ? p.Extension : Xml(p.DisplayName);
        return $"""
            <?xml version="1.0" encoding="UTF-8"?>
            <!-- Grandstream Provisioning Config — {Xml(p.DisplayName)} (Ext {p.Extension}) -->
            <!-- Phone Model: {Xml(p.PhoneModel)}  MAC: {p.MACAddress} -->
            <!-- Generated by FieldPulse SIP Readiness Tool -->
            <gs_provision version="1">
              <!-- Account 1 Settings -->
              <config name="P271" value="1"/>                     <!-- Account Active -->
              <config name="P47" value="{p.Extension}"/>          <!-- SIP User ID -->
              <config name="P35" value="[SET_PASSWORD]"/>         <!-- SIP Auth Password -->
              <config name="P36" value="{p.Extension}"/>          <!-- SIP Auth ID -->
              <config name="P270" value="{displayName}"/>         <!-- Account Name -->
              <config name="P2" value="{displayName}"/>           <!-- Display Name -->
              <config name="P47" value="{p.Extension}"/>          <!-- User ID -->
              <config name="P31" value="{Xml(server)}"/>          <!-- SIP Server -->
              <config name="P3" value="{port}"/>                  <!-- SIP Server Port -->
              <config name="P130" value="{TransportCode(transport, "grandstream")}"/>  <!-- SIP Transport -->
              <config name="P23" value="3600"/>                   <!-- Register Expiration -->
              {(string.IsNullOrEmpty(proxy) ? "" : $"<config name=\"P48\" value=\"{Xml(proxy)}\"/>  <!-- Outbound Proxy -->")}
              {(string.IsNullOrEmpty(vm) ? "" : $"<config name=\"P33\" value=\"{vm}\"/>             <!-- Voicemail ID -->")}
              <!-- Codec Preferences -->
              <config name="P57" value="0"/>                      <!-- Preferred Codec: PCMU -->
              <config name="P58" value="8"/>                      <!-- 2nd Codec: PCMA -->
            </gs_provision>
            """;
    }

    // ── Fanvil ───────────────────────────────────────────────────────
    private static string GenerateFanvil(PhoneEntry p, string server, string port, string transport, string proxy, string vm)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"## Fanvil Provisioning Config — {p.DisplayName} (Ext {p.Extension})");
        sb.AppendLine($"## Phone Model: {p.PhoneModel}  MAC: {p.MACAddress}");
        sb.AppendLine($"## Generated by FieldPulse SIP Readiness Tool");
        sb.AppendLine();
        sb.AppendLine("<<SIP1>>");
        sb.AppendLine("Enable = 1");
        sb.AppendLine($"SIPServerAddr = {server}");
        sb.AppendLine($"SIPServerPort = {port}");
        sb.AppendLine($"TransportType = {TransportCode(transport, "fanvil")}");
        sb.AppendLine($"UserName = {p.Extension}");
        sb.AppendLine($"AuthName = {p.Extension}");
        sb.AppendLine("AuthPassword = [SET_PASSWORD]");
        sb.AppendLine($"DisplayName = {(string.IsNullOrEmpty(p.DisplayName) ? p.Extension : p.DisplayName)}");
        sb.AppendLine($"Label = {(string.IsNullOrEmpty(p.DisplayName) ? p.Extension : p.DisplayName)}");
        sb.AppendLine("RegisterExpiry = 3600");
        if (!string.IsNullOrEmpty(proxy))
        {
            sb.AppendLine($"OutboundProxyAddr = {proxy}");
            sb.AppendLine($"OutboundProxyPort = {port}");
        }
        if (!string.IsNullOrEmpty(vm))
        {
            sb.AppendLine($"VoiceMailNumber = {vm}");
        }
        sb.AppendLine();
        sb.AppendLine("## Codec Config");
        sb.AppendLine("AudioCodec1 = PCMU");
        sb.AppendLine("AudioCodec2 = PCMA");
        sb.AppendLine("AudioCodec3 = G729");
        return sb.ToString();
    }

    // ── Snom ─────────────────────────────────────────────────────────
    private static string GenerateSnom(PhoneEntry p, string server, string port, string transport, string proxy, string vm)
    {
        string displayName = string.IsNullOrEmpty(p.DisplayName) ? p.Extension : Xml(p.DisplayName);
        return $"""
            <?xml version="1.0" encoding="utf-8"?>
            <!-- Snom Provisioning Config — {Xml(p.DisplayName)} (Ext {p.Extension}) -->
            <!-- Phone Model: {Xml(p.PhoneModel)}  MAC: {p.MACAddress} -->
            <!-- Generated by FieldPulse SIP Readiness Tool -->
            <settings>
              <phone-settings>
                <user_active idx="1" perm="">on</user_active>
                <user_realname idx="1" perm="">{displayName}</user_realname>
                <user_name idx="1" perm="">{p.Extension}</user_name>
                <user_host idx="1" perm="">{Xml(server)}</user_host>
                <user_srtp idx="1" perm="">off</user_srtp>
                <user_pass idx="1" perm="">[SET_PASSWORD]</user_pass>
                <user_mailbox idx="1" perm="">{(string.IsNullOrEmpty(vm) ? "" : vm)}</user_mailbox>
                {(string.IsNullOrEmpty(proxy) ? "" : $"<user_outbound idx=\"1\" perm=\"\">{Xml(proxy)}</user_outbound>")}
              </phone-settings>
            </settings>
            """;
    }

    // ── Generic (unknown brand) ──────────────────────────────────────
    private static string GenerateGeneric(PhoneEntry p, string server, string port, string transport, string proxy, string vm, string brand)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"## SIP Configuration — {brand} ({p.PhoneModel})");
        sb.AppendLine($"## Extension: {p.Extension}  Display Name: {p.DisplayName}");
        sb.AppendLine($"## MAC: {p.MACAddress}  Serial: {p.SerialNumber}");
        sb.AppendLine($"## Generated by FieldPulse SIP Readiness Tool");
        sb.AppendLine();
        sb.AppendLine("## Enter these values in your phone's web admin interface:");
        sb.AppendLine($"SIP Server       = {server}");
        sb.AppendLine($"SIP Port         = {port}");
        sb.AppendLine($"Transport        = {transport}");
        sb.AppendLine($"Username / Ext   = {p.Extension}");
        sb.AppendLine($"Auth Name        = {p.Extension}");
        sb.AppendLine("Auth Password    = [SET_PASSWORD]");
        sb.AppendLine($"Display Name     = {(string.IsNullOrEmpty(p.DisplayName) ? p.Extension : p.DisplayName)}");
        if (!string.IsNullOrEmpty(proxy))
            sb.AppendLine($"Outbound Proxy   = {proxy}");
        if (!string.IsNullOrEmpty(vm))
            sb.AppendLine($"Voicemail Ext    = {vm}");
        sb.AppendLine();
        sb.AppendLine("## Recommended Codecs (in priority order):");
        sb.AppendLine("1. G.711 u-law (PCMU)");
        sb.AppendLine("2. G.711 a-law (PCMA)");
        sb.AppendLine("3. G.729");
        return sb.ToString();
    }

    private static string BuildReadme(int phoneCount, string server, string transport)
    {
        return $"""
            ================================================================================
              FIELDPULSE SIP PROVISIONING CONFIGS
              Generated by FieldPulse SIP Readiness Tool
            ================================================================================

            This archive contains {phoneCount} provisioning configuration file(s).

            SIP Server:  {server}
            Transport:   {transport}

            IMPORTANT — BEFORE USING THESE FILES:
            ───────────────────────────────────────
            1. Replace [SET_PASSWORD] in each file with the SIP auth password
               provided by FieldPulse during onboarding.

            2. Upload configs to your provisioning server, or apply them manually:
               - Yealink:     Upload .cfg via phone web UI → Auto Provision
               - Polycom:     Upload .cfg to provisioning server (FTP/TFTP/HTTP)
               - Cisco:       Upload .cnf.xml to TFTP server
               - Grandstream: Upload .xml via phone web UI → Maintenance
               - Fanvil:      Upload .cfg via phone web UI → Auto Provision
               - Snom:        Upload .xml to provisioning server (HTTP/HTTPS)

            3. After applying, reboot each phone to register with the new config.

            NEED HELP?
            ──────────
            Contact your FieldPulse representative or email support@fieldpulse.com

            ================================================================================
            """;
    }

    private static string Xml(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");
}
